### ISSUE TITLE
optional Int64 argument in an interface

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/hxcpp#225]
Native compilation failed for the following example.

```haxe
interface ITest {
	public function reset(?init:haxe.Int64):Void;
}

class Test {
	static function main() {

	}
}
```

It works with haxe 3.1.3 + hxcpp 3.2.37, but not with haxe dev + hxcpp dev.

**Comment by andyli** [comment]
Thanks for fixing!
But look like you've accidentally changed haxelib submodule?

**Comment by hughsando** [comment]
How the hell did that happen.  I never use -a, only explicitly list the
files.
I guess it is easiest to make a commit to restore that file?

**Comment by andyli** [comment]
Yes, a new commit to restore that file would be the best choice since it is generally a bad idea to alter the history of main branch.

Maybe you can try to use a GUI for git. I'm using SourceTree on both Mac and Windows and it avoids this kind of accident since it always display the staged/unstaged changes. And the whole git branching concept has always been graphical to me, so using gui is even more natural to the command line.

**Comment by hughsando** [comment]
Actually, it appears that it is the change is the submodule id - any hints on how to reverse this?

**Comment by andyli** [comment]
1. cd to extra/haxelib_src
2. checkout the target commit
3. cd back to haxe src root
4. add extra/haxelib_src to staged change, and commit

**Comment by hughsando** [comment]
Thanks a lot - I think that did the trick.
