### ISSUE TITLE
Can't compile on Mac

### ISSUE THREAD

**Issue by josephsmendoza** [HaxeFoundation/hxcpp#878]
Trying to build a haxeui-hxwidgets program, compiles fine on windows and linux, on Mac 10.15.1 I get #819   

```
Compiling group: runtime
g++ -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H -c -fvisibility=hidden -stdlib=libc++ -Qunused-arguments -O2 -I/usr/local/Cellar/haxe/4.0.5/lib/haxe/lib/hxcpp/4,0,64/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -Wno-overflow -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) ... tags=[haxe]
 - src/hx/Date.cpp
 - src/Array.cpp
 - src/hx/Boot.cpp
 - src/hx/Interface.cpp
 - src/hx/Object.cpp
 - src/hx/Anon.cpp
Error: /usr/local/Cellar/haxe/4.0.5/lib/haxe/lib/hxcpp/4,0,64/src/Array.cpp:390:28: error: use of undeclared identifier 'u'
            memcpy(buf+pos,u"null",8);
                           ^
1 error generated.
Error: Build failed
```

**Comment by hughsando** [comment]
I wonder of gcc needs the  -std=c++11 flag too.
toolchain/mac-toolchain.xml uses the 'unless' clause to stop this:

` <cppflag value="-std=c++11" if="HXCPP_CPP11" unless="HXCPP_GCC"/>`

You could try removing the "unless" clause.
I presume you are deliberately using gcc rather than xcode/clang, which is what has been better tested.

**Comment by josephsmendoza** [comment]
I didn't specifically choose GCC, at least not that I can remember. To set this machine up I ran `xcode-select --install` and `brew install haxe`. I'm not too familiar with the c++ build system, how would I switch to clang?

**Comment by josephsmendoza** [comment]
Found this in `mac-toolchain.xml`
```
<compiler id="darwin" exe="g++" if="macos">
  <exe name="xcrun --sdk macosx${MACOSX_VER} clang++" if="HXCPP_CLANG" />
```
Tried adding `-D HXCPP_CLANG` to my `hxwidgets.hxml` and got the same error:
```
Compiling group: runtime
xcrun --sdk macosx clang++ -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H -c -fvisibility=hidden -stdlib=libc++ -Qunused-arguments -O2 -I/usr/local/Cellar/haxe/4.0.5/lib/haxe/lib/hxcpp/4,0,64/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-overflow -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) ... tags=[haxe]
 - src/Dynamic.cpp
 - src/Math.cpp
 - src/hx/gc/GcRegCapture.cpp  [haxe,gc]
 - src/Array.cpp
 - src/hx/Hash.cpp
 - src/hx/Thread.cpp
Error: /usr/local/Cellar/haxe/4.0.5/lib/haxe/lib/hxcpp/4,0,64/src/Array.cpp:390:28: error: use of undeclared identifier 'u'
            memcpy(buf+pos,u"null",8);
                           ^
1 error generated.
Error: Build failed
```
Removing the "unless" clause fixes the issue for GCC and clang.
