### ISSUE TITLE
"error: no viable conversion from 'hx::Null<bool>' to 'bool'" in simple program

### ISSUE THREAD

**Issue by DanielUranga** [HaxeFoundation/hxcpp#189]
This sample program:

```haxe
typedef BitmapData = { foo : String };

class Main {

	public static function getBitmapData2(id:String, useCache:Bool = true) {
		return null;
	}

	static dynamic public function getBitmapData(src:String, useCache:Bool = true) : BitmapData {
        return getBitmapData2(src, useCache);
    }

	static function main() {
		getBitmapData("test");
	}

}
```

Fails to compile in cpp compile stage with this error:
```
g++ -Iinclude -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/Users/dokkogroup/Documents/haxe/hxcpp/include -DHX_MACOS -m32 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -x c++ -frtti -Wno-invalid-offsetof ./src/Main.cpp -oobj/darwin/ae7b103b_Main.o
Error: ./src/Main.cpp:50:7: error: no viable conversion from 'hx::Null<bool>' to 'bool'
        bool tmp1 = useCache;           HX_STACK_VAR(tmp1,"tmp1");
             ^      ~~~~~~~~
/Users/dokkogroup/Documents/haxe/hxcpp/include/null.h:164:11: note: candidate function
   inline operator Dynamic();
          ^
1 error generated.
```

**Comment by Simn** [comment]
Seems to work in 3.1.3.

**Comment by hughsando** [comment]
It was possibly compiling but not working depending on defaults values in 3.1.3
