### ISSUE TITLE
Android - "hxcpp.h: No such file or directory"

### ISSUE THREAD

**Issue by jskuse** [HaxeFoundation/hxcpp#494]
I'm trying to get to the bottom of a hornet's nest of issues building our project for Android for the first time since moving to hxcpp 3.3.49. Our native code component, which is heavily modelled in structure on the linc_ libraries, won't build on Android (but Mac and iOS are fine). Reverting to hxcpp 3.2.94 makes this particular error go away (but unfortunately can't be a long term solution for us because it has _other_ issues with the most recent NDK). I've tried the git version and the results are the same.

As a diagnostic, I tried to build https://github.com/snowkit/linc_empty (because it's a _lot_ less complex), which shows the same results (doesn't exhibit this error on 3.2.94, builds ok with 3.3.49 for iOS and Mac). Of course, there's every chance this isn't a HXCPP issue at all, but any suggestion would be welcome because we're really up against the clock.

```
/Users/jskuse/Documents/development/linc_empty//linc/linc_empty.h:6:19: fatal error: /Users/jskuse/Documents/development/linc_empty/test/cpp/obj/android/__pch/haxe/hxcpp.h: No such file or directory
 #include <hxcpp.h>
```

In the `/test/cpp/obj/android/__pch/haxe/` directory, there is a `hxcpp.h.gch` file only.

In case it helps, the full error is:

```
Error: While running :arm-linux-androideabi-g++ -I/Users/jskuse/Documents/development/linc_empty/test/cpp/obj/android/__pch/haxe -Iinclude -I/Users/jskuse/Documents/development/linc_empty//linc/ --sysroot=/opt/android-ndk/platforms/android-24/arch-arm -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -I/usr/local/lib/haxe/lib/hxcpp/3,3,49/include -Iinclude -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -DHXCPP_CPP11 -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -march=armv5te -mtune=xscale -msoft-float -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limit=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=24 -Wa,--noexecstack -O2 -DNDEBUG -c -x c++ -Wno-invalid-offsetof -frtti -std=c++11 ./src/Test.cpp -o/Users/jskuse/Documents/development/linc_empty/test/cpp/obj/android/81ab12f9_Test.obj
In file included from ./src/Test.cpp:3:0:
/Users/jskuse/Documents/development/linc_empty//linc/linc_empty.h:6:19: fatal error: /Users/jskuse/Documents/development/linc_empty/test/cpp/obj/android/__pch/haxe/hxcpp.h: No such file or directory
 #include <hxcpp.h>
                   ^
compilation terminated.
```

**Comment by eliasku** [comment]
the same for me

**Comment by eliasku** [comment]
Solved for me by `-D NO_PRECOMPILED_HEADERS`

**Comment by Hero7785** [comment]
Where would I put the -D NO_PRECOMPILED_HEADERS next to where I build and it still creates a .h.gch file

**Comment by hughsando** [comment]
I think this is closed by:
https://github.com/underscorediscovery/luxe/issues/385

**Comment by jcward** [comment]
Cross-links all around. :P 

Some more recent (Linux-specific) discussion about here: https://github.com/HaxeFoundation/hxcpp/issues/559#issuecomment-318958353

**Comment by Lelelo1** [comment]
After having compiled on mac to cpp, I also have the `hxcpp.h` file missing. Specifying `-D NO_PRECOMPILED_HEADERS` in my `cppBuil.hxml` file does not make any difference, like eliasku suggested

**Comment by hughsando** [comment]
This sounds like something different and something funky with your install. You can compile with "-D HXCPP_VERBOSE" to get more output.  If you are still having an issue, perhaps open a new issue and post the full output of compiling a simple program with this flag on.
