### ISSUE TITLE
Native iOS extension works with 3.1.48 and crashes with 3.1.39

### ISSUE THREAD

**Issue by sergey-miryanov** [HaxeFoundation/hxcpp#157]
Hi, I'm note sure that this is a hxcpp issue. But maybe you can shed light and point me a right direction.

I created iOS extension for Flurry and on hxcpp 3.1.48 and lime 2.0.4 it works fine. But for hxcpp 3.1.39 and lime 2.0.1 it crashes after start with following output:
```
Primitive not found : startSession__1
Primitive not found : setCrashReportingEnabled__1
Primitive not found : logEvent__4
Primitive not found : endTimedEvent__3
Primitive not found : setUserId__1
Primitive not found : setGender__1
Primitive not found : setAge__1
Primitive not found : logPageView__0
Primitive not found : setAppVersion__1
Primitive not found : setEventLoggingEnabled__1
Primitive not found : setLogLevel__1
Primitive not found : setSessionContinueSeconds__1
Null Function Pointer
Called from *._Function_1_2 (ApplicationMain.hx line 91)
Called from Type.createInstance (/usr/lib/haxe/std/cpp/_std/Type.hx line 82)
Called from DocumentClass.new (ApplicationMain.hx line 141)
Called from Main.new (Main.hx line 35)
Called from Main.testFlurry (Main.hx line 54)
Called from ru.zzzzzzerg.linden.FlurryIOS.onStartSession (ru/zzzzzzerg/linden/Flurry.hx line 288)
```

I have issue in my repo https://github.com/sergey-miryanov/linden-flurry/issues/10.

I have no clue what wrong and what I should do. I tried to patch ios*-toolchain in 3.1.39 but without luck. Also I tried to use 3.1.39 built libs in lime 2.0.4 but can't figure how to build without 64bit support.

I appreciate any input from you.

**Comment by hughsando** [comment]
Did you try 3.1.48 with lime 2.0.1? ie, is it a lime issue or a hxcpp issue?
The main file for this code is "src/hx/Lib.cpp" - you could try copying
this file from 3.1.48 to 3.1.39 and see if this helps.  The other thing may
be an order-of-initialization issue, but I think this would be haxe
related, rather than hxcpp related.

**Comment by sergey-miryanov** [comment]
If I build with 3.1.48 and lime 2.0.1 - application build ok, but can't run with error:
```
Session could not be started: Error Domain=FBSOpenApplicationErrorDomain Code=4 "Unable to run app in Simulator" UserInfo=0x7ff273fbade0 {NSUnderlyingError=0x7ff273fba370 "The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)", NSLocalizedFailureReason=An error was encountered while running (Domain = FBSOpenApplicationErrorDomain, Code = 4), NSLocalizedDescription=Unable to run app in Simulator}
```


If I copy Lib from 3.1.48 to 3.1.39 I got following error:
```
Undefined symbols for architecture i386:
  "__hxcpp_get_proc_address(String, String, bool)", referenced from:
      __hxcpp_run_dll(String, String) in libApplicationMain.a(3a602ec4_Lib.o)
     (maybe you meant: __Z24__hxcpp_get_proc_address6StringS_bb)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
