### ISSUE TITLE
No cpp::Pointer_obj::fromRaw(cpp::RawAutoCast) on haxe 3.2.1

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hxcpp#444]
Changed code from `Pointer.fromRaw(untyped __cpp__("(wxTextCtrl*)(_ref->get_raw())"));` to the lot nicer `Pointer.fromRaw(_ref.rawCast());`.

But this code

```
private function get_textCtrlRef():Pointer<WxTextCtrl> {
    return Pointer.fromRaw(_ref.rawCast());
}
```

(with `_ref` a `Pointer<WxWindow>` and `WxWindow` a parent class of `WxTextCtrl`)

fails on c++ compilation with

```
./src/hx/widgets/TextCtrl.cpp:183:87: error: no matching function for call to ‘cpp::Pointer_obj::fromRaw(cpp::RawAutoCast)’

./src/hx/widgets/TextCtrl.cpp:183:87: note: candidates are:

/home/travis/build/ianharrigan/hxWidgets/hxcpp/include/cpp/Pointer.h:487:27: note: template<class T> static cpp::Pointer<T> cpp::Pointer_obj::fromRaw(T*)

/home/travis/build/ianharrigan/hxWidgets/hxcpp/include/cpp/Pointer.h:489:27: note: template<class T> static cpp::Pointer<T> cpp::Pointer_obj::fromRaw(const T*)
```

on haxe 3.2.1, works on 3.3.

**Comment by ibilon** [comment]
Looking into it, no luck yet, I can't find in `cpp::Pointer`, `cpp::Pointer_obj` or `cpp::RawAutoCast` anything related to this and the haxe version.

But made a small test case:
```haxe
import cpp.Pointer;
import cpp.RawPointer;

@:headerCode("
class Parent {
public:
	Parent() { }
};

class Child : public Parent {
public:
	Child():Parent() { }
};
")
class Test {
	public static function main() {
		var c = Pointer.fromRaw(Child._new());
		var p = conv(c);
	}

	static inline function conv(c:Pointer<Child>):Pointer<Parent> {
		return Pointer.fromRaw(c.rawCast());
	}
}

extern class Parent {
	@:native("new Parent") public static function _new():RawPointer<Parent>;
}

extern class Child extends Parent {
	@:native("new Child") public static function _new():RawPointer<Child>;
}
```

**Comment by ibilon** [comment]
Found the difference,
in haxe 3.3 it gives the following c++ code:
```c++
::Parent* _hx_tmp1 = c->rawCast();
::cpp::Pointer_obj::fromRaw(_hx_tmp1);
```

but in 3.2.1:
```
::cpp::Pointer< Parent > p = ::cpp::Pointer< Parent >(::cpp::Pointer_obj::fromRaw(c->rawCast()));
```
hence the
```
error: no matching function for call to ‘cpp::Pointer_obj::fromRaw(cpp::RawAutoCast)
```

**Comment by ibilon** [comment]
Just realized that `Pointer.fromRaw(_ref.rawCast())` is `_ref.reinterpret()`,
I guess I tried to remove the untyped __cpp__ without looking at the whole line,
well now it works for my code.

@hughsando is the original issue supposed to work? if not feel free to close.

**Comment by hughsando** [comment]
I'll close this now.
In the latest code, "cpp.Star<Type>" requires less messing about with than cpp.Pointer.
