### ISSUE TITLE
[IOS] Matrix3D build error

### ISSUE THREAD

**Issue by srevid** [HaxeFoundation/hxcpp#471]
I have a error while building for ios on El Capitan with the 3.3 version of haxe.

The build work with OpenFL 3.6.1 and lime 2.9.1 with the version 3.3 of Haxe, but if i downgrade the version of OpenFL to 3.6.0, build fail with this error :

`Error: While running :xcrun --sdk iphoneos9.3 clang++ -I/Users/affranchis/Documents/Haxe/AFDT/Export/ios/AFDT/haxe/build/Release-iphoneos-v7/obj/iphoneos-c11-v7/__pch/haxe -Iinclude -c -stdlib=libc++ -O2 -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -miphoneos-version-min=5.0 -fobjc-arc -DOBJC_ARC -DENABLE_BITCODE=YES -fembed-bitcode -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-bool-conversion -fno-stack-protector -DIPHONE=IPHONE -DIPHONEOS=IPHONEOS -DSTATIC_LINK -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -I/usr/local/lib/haxe/lib/hxcpp/3,3,49/include -fexceptions -fstrict-aliasing -x c++ -Wno-invalid-offsetof ./src/openfl/geom/Matrix3D.cpp -o/Users/affranchis/Documents/Haxe/AFDT/Export/ios/AFDT/haxe/build/Release-iphoneos-v7/obj/iphoneos-c11-v7/8f922b90_Matrix3D.o
./src/openfl/geom/Matrix3D.cpp:519:122: error: no member named 'StaticCast' in 'Array<Dynamic>'
HXLINE( 361)            HX_VARI_NAME( ::Array< ::Dynamic>,this1,"this") = ::Array_obj< ::Dynamic>::__new()->__SetSizeExact(null()).StaticCast< ::Array< ::Dynamic> >();
                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
./src/openfl/geom/Matrix3D.cpp:519:154: error: expected '(' for function-style cast or type construction
HXLINE( 361)            HX_VARI_NAME( ::Array< ::Dynamic>,this1,"this") = ::Array_obj< ::Dynamic>::__new()->__SetSizeExact(null()).StaticCast< ::Array< ::Dynamic> >();
                                                                                                                                               ~~~~~~~~~~~~~~~~~~~ ^
./src/openfl/geom/Matrix3D.cpp:519:156: error: expected expression
HXLINE( 361)            HX_VARI_NAME( ::Array< ::Dynamic>,this1,"this") = ::Array_obj< ::Dynamic>::__new()->__SetSizeExact(null()).StaticCast< ::Array< ::Dynamic> >();
                                                                                                                                                                     ^
3 errors generated.
make: *** [build-haxe-armv7] Error 1`

If i downgrade my version of Haxe to 3.2, build work perfectly with any version of OpenFL.

System : 
El Capitan 10.11.15
Xcode 7.3.1
Ios SDK : iphoneos-9.3
OpenFL 3.6.1
Lime 2.9.1
Hxcpp: 3.3.49 [don't work] - 3.2.205 [work]

**Comment by hughsando** [comment]
This appears to be using  the Vector construct ` new Vector<Vector3D> ();`, which is causing your problem.
But when I try this on my machine, I get
```
HXLINE( 361)		HX_VARI_NAME( ::Array< ::Dynamic>,this1,"this") = _hx_array_set_size_exact(::Array_obj< ::Dynamic>::__new(),null());
```
which does not use ```__SetSizeExact```
So to me, it looks like you may be using the new version of haxe, but with the old haxe/std version of "Vector.hx", which can cause problems.
This can be controlled with symbolic linking or the HAXE_STD_PATH environment variable.  How are you switching between versions of haxe?

**Comment by srevid** [comment]
I just reinstall the old version of haxe with the installer.
But i install Haxe 3.3 just after the upgrade to El Capitan. Maybe there was dirt in the system after that and the new haxe was spoil.

**Comment by hughsando** [comment]
Yes, mac has had some issues with the directory haxe is installed in, since one of the directories (/usr/local/lib ? from memory) is no longer available in El Capitan.  So I think you have an old version of std installed somewhere on your system.  You  can use 'haxe -v -main Something" and it will print out its classpath.

**Comment by srevid** [comment]
Thanks for your help !
