### ISSUE TITLE
incorrect code for enum

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hxcpp#422]
Using hxcpp dev this code:
```haxe
class Test
{
	public static function main ()
	{
		trace(haxe.io.Error.Blocked);
	}
}
```

generate this:
```c++
#ifndef INCLUDED_haxe_io_Error
#define INCLUDED_haxe_io_Error

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(haxe,io,Error)
namespace haxe{
namespace io{


class Error_obj : public hx::EnumBase_obj
{
	typedef hx::EnumBase_obj super;
		typedef Error_obj OBJ_;

	public:
		Error_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		::String GetEnumName( ) const { return HX_HCSTRING("haxe.io.Error","\x68","\x16","\x01","\x55"); }
		::String __ToString() const { return HX_HCSTRING("Error.","\x86","\xf7","\xfc","\x85") + tag; }

		static ::haxe::io::Error Blocked;
		static inline ::haxe::io::Error Blocked_dyn() { return Blocked; }
		static ::haxe::io::Error Custom(Dynamic e);
		static Dynamic Custom_dyn();
		static ::haxe::io::Error OutsideBounds;
		static inline ::haxe::io::Error OutsideBounds_dyn() { return OutsideBounds; }
		static ::haxe::io::Error Overflow;
		static inline ::haxe::io::Error Overflow_dyn() { return Overflow; }
};

} // end namespace haxe
} // end namespace io

#endif /* INCLUDED_haxe_io_Error */ 
```

which fails with:
```
Error: In file included from ./src/Test.cpp:10:0:
include/haxe/io/Error.h: In member function ‘virtual String haxe::io::Error_obj::__ToString() const’:
include/haxe/io/Error.h:24:92: error: ‘tag’ was not declared in this scope
   ::String __ToString() const { return HX_HCSTRING("Error.","\x86","\xf7","\xfc","\x85") + tag; }
```

Worked on hxcpp 3.2.205.
